[#-- a banner to be displayed when the space taken by artifacts exceeds the hard limit --]
[#if ctx.featureManager.artifactStorageSpaceLimited]
    [#assign userLoggedIn = ctx.getUser(req)?? /]
    [#if userLoggedIn && ctx.storageCappingService.hardLimitExceeded]
        [@ui.banner cssClass='storage-hard-limit-warning-banner']
        <strong>
            [#if ctx.hasAdminPermission()]
                [#if ctx.featureManager.atlassianAgents]
                    [@s.text name="storage.capping.warning.banner.admin.aa" /]
                [#else]
                    [@s.text name="storage.capping.warning.banner.admin"]
                        [@s.param][@s.url namespace='/admin' action='configureArtifactStorage' /][/@s.param]
                    [/@s.text]
                [/#if]
            [#else]
                [#if ctx.featureManager.atlassianAgents]
                    [@s.text name="storage.capping.warning.banner.nonAdmin.aa" /]
                [#else]
                    [@s.text name="storage.capping.warning.banner.nonAdmin" /]
                [/#if]
            [/#if]
        </strong>
        [/@ui.banner]
    [/#if]
[/#if]
